### PR TITLE
fixing race conditions in tests

### LINKED ISSUE #28: Test reliant on timing causing nondeterministic results
It looks like there's a timing issue in this test even with nanoseconds being the timestamp. Maybe replace all instances of the `%N` with millis and nanos and add a sleep (or mock the calls to `Time`).

https://github.com/logstash-plugins/logstash-output-google_cloud_storage/blob/db32da1aea5e7980da1d3fb200a7f9530e6095f6/spec/outputs/gcs/path_factory_spec.rb#L117

It's causing this error to show up in CI:

https://travis-ci.org/logstash-plugins/logstash-output-google_cloud_storage/jobs/379924151

### PR DESCRIPTION
**Pull request by josephlewis42**
Fixes #28 as far as I can tell. I ran with the same seed before and after the changes and it went from failing to passing.

The problems were that some background threads were being started by a few tests and weren't cleaned up at the end so they were triggering events in other tests.

### CODE REVIEW

File: lib/logstash/outputs/google_cloud_storage.rb [hunk 1]
```diff
@@ -175,7 +175,7 @@ def receive(event)
   public
   def close
     @logger.debug('Stopping the plugin, uploading the remaining files.')
-    Stud.stop!(@registration_thread) unless @registration_thread.nil?
+    Thread.kill(@uploader_thread) unless @uploader_thread.nil?
```
Comment (rosbo) [inline lib/logstash/outputs/google_cloud_storage.rb]: Should you also stop the registration thread?

Comment (josephlewis42) [reply lib/logstash/outputs/google_cloud_storage.rb]: I replaced registration thread with uploader thread because `Stud::` was calling `kill` in the background anyway but something went wonky when doing it with the tests which left orphaned threads running.

I wish there was something that would be more fluent like:

```.ruby
Background.every 30.seconds do
	# ...
end
```
